### ISSUE TITLE
better formatted as a wiki?

### ISSUE THREAD

**Issue by Lupus590** [CC-Play-by-post-RPG/Lore#1]

**Comment by KnightMiner** [comment]
I think either one could work.

The main advantage of a repository is that it is easier as a game master to control it while still allowing contributions (to prevent facts from being changed at bad points, though I don't see any of our current users doing that); meanwhile a wiki is a better layout for information overall.

**Comment by Lupus590** [comment]
We can try the wiki, if we get a lot of problems then we will use the repo
