### ISSUE TITLE
Articles on characters

### ISSUE THREAD

**Issue by KnightMiner** [CC-Play-by-post-RPG/Lore#2]
How do you plan on formatting character articles? Do you just want to copy the information over into a markdown table, or do you want to reformat to a little more like a wikipedia character article? 

Also, I cannot seem to edit the wiki, so can I be added as a collaborator?

**Comment by Lupus590** [comment]
Wiki like I'm thinking, but a summary table may be a good idea too

edit: added you

**Comment by Lupus590** [comment]
I've changed the settings so that people don't have to be a collaborator to push to the wiki, if we get problems then I can set it back

(Note to future me: https://help.github.com/articles/changing-access-permissions-for-wikis/)

**Comment by KnightMiner** [comment]
Another couple questions:
- How do you want character articles named: nickname or full name? I personally prefer full name, but since Github wikis don't seem to support redirects (thus you would always have to type the full name), nick names seem like the easier option.
-  Do you want characters hidden from the sidebar? Github supports adding a custom sidebar which causes the default to collapse, which I'd prefer as a solution so the sidebar does not get so cluttered with characters, though it would require manually editing the sidebar when new pages are added (if you want them there)

**Comment by Lupus590** [comment]
I was thinking of having an index of player characters, with this index appearing on the side bar
Custom sidebar is a good idea, and will be required for the above to be effective
nick names is probably a good idea, although we could do manual redirects (empty page with a link sounds wasteful though)

**Comment by KnightMiner** [comment]
I've created a character index of sorts [here](/CC-Play-by-post-RPG/Lore/wiki/Player Characters), though an index in the sidebar could be helpful as well.

My major concern with that is with the amount of characters we have, that list could get quite large. If there was a way to make part of the side bar collapsible, or otherwise having a separate sidebar based on page, that would prevent such clutter.

**Comment by Lupus590** [comment]
It's player characters, not playable characters

edit: fixed already, please update any links to that page

retired characters don't need to be in the sidebar

perhaps the custom sidebar should only include "top level" items? so I I wanted to find a particular PC I would first navigate to the pc page and then scroll down to the player character I was looking for

**Comment by KnightMiner** [comment]
Top level items only could work, the index on the PC page should be good enough for someone to find a character, and give a decent "category" structure.

I switched the player character index to link nick names rather than full ones. I've also written up the first draft of a character article [here](/CC-Play-by-post-RPG/Lore/wiki/Matthias), opinions? Some specific things to note:
- Since I wanted to not have a row of headers at the top, I had to use MediaWiki markup over markdown (which is a bit less intuitive since it is a very stripped down form of MediaWiki). There does not appear to be a way to apply CSS to the table though, and it looks a little odd on the left (I was trying for a Wikipedia style Infobox) Would it be better to write that part as a paragraph?
- I rearranged a few of the fields a bit, most notably making "Attire" a subpoint of "Appearance" and placing "Skills" (pros and cons, plus the "Weaponry" section I added to my characters) last. I want to have it a bit more orgnaized using the sub headers, but no direct categories come to me other than the skills
- I added two additions to the history: "Entrance" and "Exit", which are designed to fill the gap between the early history and the character meeting the party, and how they left the party if relevant. I want to add history between the two, but I figured that would basically become a plot summary.

**Comment by Lupus590** [comment]
I like the entrance and exit idea, as with all of the sub sections.
Having read the entire thing, looks good so far, some things seem to be limitations of the github wiki markdown formats.

**Comment by KnightMiner** [comment]
I'll start converting a few other characters over then. I think I'll start by doing my characters, and post on the RPG thread to see if anyone else wants to convert their own characters. If people don't seem to want to do it themselves, I'll just convert them over in a few days.

**Comment by Lupus590** [comment]
Having a template page for characters will be helpful

**Comment by KnightMiner** [comment]
Yeah, sorry about not finishing anything. I wasn't entirely happy with how it turned out and then became quite busy IRL before finishing anything. Looking at what I have now I don't think I could make much better, so I will make a template from there

**Comment by KnightMiner** [comment]
So, I have the [character template](/CC-Play-by-post-RPG/Lore/wiki/Character-Template) written up, plus my two characters ported. Do you want to see how well I explained everything by porting Night-Wanderer to the wiki? After that we can see about other users porting their characters over (as they may want to update a few things, plus there are the new combat section and tweaked history). After we give users a chance to port, I can work on porting the inactive characters.

**Comment by Lupus590** [comment]
Sounds good, I'll get porting.

Edit: having just read the first 3 instruction paragraphs, it seems fine. ~~I'm guessing that the other stuff in the entries are in the style of the original template character sheet~~ It does.

Unless we have any future problems, I believe this issue can be closed.
